//! Generic client operations over [`Resource`], [`SingletonResource`], and [`CollectionSingletonResource`].
//!
//! | Operation                  | Method                                  | Endpoint shape              |
//! |----------------------------|-----------------------------------------|-----------------------------|
//! | Fetch singleton            | `client.fetch_singleton::<TokenInfo>()` | Fixed URL, one object       |
//! | Fetch collection singleton | `client.fetch_collection::<Bank>()`     | Fixed URL, `Vec`            |
//! | Fetch by ID                | `client.get::<Item>(id)`                | `/{path}/{id}`              |
//! | Fetch many by ID           | `client.get_many::<Item>(ids)`          | `/{path}?ids=1,2,3`         |
//! | List all IDs               | `client.list_ids::<Item>()`             | `/{path}` (no args)         |
//! | Fetch all                  | `client.all::<Item>()`                  | `?ids=all` or all pages     |
//! | Stream pages               | `client.pages::<Item>(opts)`            | `?page=N&page_size=M`       |

use std::collections::{HashMap, HashSet};

use async_stream::stream;
use serde::de::DeserializeOwned;
use futures::{Stream, TryStreamExt};

use crate::client::Gw2Client;
use crate::client::auth::AuthState;
use crate::error::Gw2ApiError;

use super::{CollectionSingletonResource, PagedResource, Patchable, Resource, SingletonResource};

/// Options for paginated streaming.
#[derive(Debug, Clone)]
pub struct PageOptions {
    /// The page number to start from (0-indexed). Default: 0.
    pub start_page: u32,
    /// Stop after this page number (exclusive). `None` streams until exhausted.
    pub end_page: Option<u32>,
    /// Items per page (1–200). Default: 50.
    pub page_size: u32,
}

impl Default for PageOptions {
    fn default() -> Self {
        Self {
            start_page: 0,
            end_page: None,
            page_size: 50,
        }
    }
}

impl PageOptions {
    /// Set the page size (clamped to 1–200).
    pub fn page_size(mut self, size: u32) -> Self {
        self.page_size = size.clamp(1, 200);
        self
    }

    /// Stream only pages in `start..end`.
    pub fn range(mut self, start: u32, end: u32) -> Self {
        self.start_page = start;
        self.end_page = Some(end);
        self
    }
}

// ── Singleton operations ────────────────────────────────────────────────────

impl<S: AuthState> Gw2Client<S> {
    /// Fetch a singleton resource (no ID required).
    ///
    /// For auth-only singletons, prefer the typed accessor generated by
    /// `#[gw2_endpoint(path = "...", auth)]`, which restricts the call to
    /// `Gw2Client<Authenticated>`.
    pub(crate) async fn fetch_singleton<R: SingletonResource>(&self) -> Result<R, Gw2ApiError> {
        self.request(format!("/{}", R::PATH)).send().await
    }
}

impl<S: AuthState> Gw2Client<S> {
    /// Fetch a collection singleton resource (fixed URL, returns `Vec<Item>`).
    ///
    /// Used for account sub-resources like `/v2/account/wallet`, `/v2/account/bank`, etc.
    /// These live at a fixed URL (no ID), but return a list rather than a single object.
    pub(crate) async fn fetch_collection<R: CollectionSingletonResource>(
        &self,
    ) -> Result<Vec<R::Item>, Gw2ApiError> {
        self.request(format!("/{}", R::PATH)).send().await
    }
}

impl<S: AuthState> Gw2Client<S> {
    /// Fetch every page of a fixed-URL, paginated list (e.g. `/v2/commerce/transactions/…`).
    ///
    /// Requests `page_size=200` until a page comes back short, or a page past the end
    /// answers 400 (the API never returns an empty page). A 400 on the first page is an error.
    pub(crate) async fn fetch_all_pages<T: DeserializeOwned>(&self, path: &str) -> Result<Vec<T>, Gw2ApiError> {
        const PAGE_SIZE: u32 = 200;
        let mut all = Vec::new();
        for page in 0.. {
            match self.request(path).page(page, PAGE_SIZE).send::<Vec<T>>().await {
                Ok(items) => {
                    let short = items.len() < PAGE_SIZE as usize;
                    all.extend(items);
                    if short {
                        break;
                    }
                }
                Err(Gw2ApiError::BadRequest(_)) if page > 0 => break,
                Err(e) => return Err(e),
            }
        }
        Ok(all)
    }
}

// ── Multi-resource operations ───────────────────────────────────────────────

impl<S: AuthState> Gw2Client<S> {
    /// Fetch a single resource by ID.
    ///
    /// Results are cached in the shared static cache (unless the resource is `auth`).
    /// Concurrent requests for the same ID share one fetch.
    ///
    /// Known API bugs are corrected automatically via [`Patchable::patch`], before
    /// the value is cached.
    pub(crate) async fn get<R: Resource + Patchable>(
        &self,
        id: impl Into<R::Id>,
    ) -> Result<R, Gw2ApiError> {
        // Accepts raw u32 or typed newtype (e.g. ItemId) interchangeably.
        // Typed newtypes don't catch wrong-value mistakes (ItemId(999) is just as wrong
        // as 999), so requiring the wrapper buys no safety — only boilerplate.
        // Shim pattern: converts here and delegates so the heavy body in get_by_id
        // monomorphizes once per R, not once per (R × Into implementor).
        self.get_by_id(id.into()).await
    }

    async fn get_by_id<R: Resource + Patchable>(&self, id: R::Id) -> Result<R, Gw2ApiError> {
        let fetch = async {
            let mut value: R = self.request(format!("/{}/{}", R::PATH, id)).send().await?;
            value.patch();
            Ok(value)
        };
        if R::AUTH {
            return fetch.await;
        }
        self.inner
            .cache
            .get_or_fetch::<R, _>(&self.inner.cache_scope, &id, fetch)
            .await
    }

    /// Store freshly fetched, already patched values in the static cache.
    async fn cache_all<R: Resource>(&self, items: &[R]) {
        if R::AUTH || !self.inner.cache.is_enabled() {
            return;
        }
        for item in items {
            self.inner
                .cache
                .insert::<R>(&self.inner.cache_scope, item.id(), item.clone())
                .await;
        }
    }

    /// Fetch multiple resources by IDs.
    ///
    /// Duplicate IDs are requested once; cached IDs are not requested at all; the
    /// rest go out as `?ids=` in chunks of 200. The result follows the order of
    /// `ids` (duplicates included). IDs the API does not return are left out.
    ///
    /// Known API bugs are corrected automatically via [`Patchable::patch`].
    pub(crate) async fn get_many<R: Resource + Patchable>(
        &self,
        ids: impl IntoIterator<Item = R::Id>,
    ) -> Result<Vec<R>, Gw2ApiError> {
        const CHUNK_SIZE: usize = 200;

        let ids: Vec<R::Id> = ids.into_iter().collect();
        let cacheable = !R::AUTH && self.inner.cache.is_enabled();

        let mut found: HashMap<R::Id, R> = HashMap::with_capacity(ids.len());
        let mut misses: Vec<R::Id> = Vec::new();
        let mut seen: HashSet<&R::Id> = HashSet::with_capacity(ids.len());
        for id in &ids {
            if !seen.insert(id) {
                continue;
            }
            if cacheable
                && let Some(hit) = self.inner.cache.get::<R>(&self.inner.cache_scope, id).await {
                    found.insert(id.clone(), hit);
                    continue;
                }
            misses.push(id.clone());
        }

        for chunk in misses.chunks(CHUNK_SIZE) {
            let mut fetched: Vec<R> = self
                .request(format!("/{}", R::PATH))
                .ids(chunk.iter())
                .send()
                .await?;
            for item in &mut fetched {
                item.patch();
            }
            self.cache_all(&fetched).await;
            found.extend(fetched.into_iter().map(|item| (item.id().clone(), item)));
        }

        Ok(ids.iter().filter_map(|id| found.get(id).cloned()).collect())
    }

    /// List all IDs for a resource type.
    ///
    /// Equivalent to Python's `await Item.all(expanded=False)`.
    pub(crate) async fn list_ids<R: Resource>(&self) -> Result<Vec<R::Id>, Gw2ApiError> {
        self.request(format!("/{}", R::PATH)).send().await
    }

    /// Fetch all resources of this type.
    ///
    /// Tries `?ids=all` first; on [`Gw2ApiError::BadRequest`] (endpoint doesn't support it),
    /// falls back to full pagination. Equivalent to Python's `await Item.all(expanded=True)`.
    pub(crate) async fn all<R: PagedResource + Patchable>(&self) -> Result<Vec<R>, Gw2ApiError> {
        match self
            .request(format!("/{}", R::PATH))
            .param("ids", "all")
            .send::<Vec<R>>()
            .await
        {
            Ok(mut results) => {
                for item in &mut results {
                    item.patch();
                }
                self.cache_all(&results).await;
                Ok(results)
            }
            Err(Gw2ApiError::BadRequest(_)) => {
                // Endpoint doesn't support ids=all — collect all pages
                self.pages::<R>(PageOptions::default().page_size(200))
                    .try_collect()
                    .await
            }
            Err(e) => Err(e),
        }
    }

    /// Stream all resources page by page.
    ///
    /// Equivalent to Python's `async for item in Item.pages(...)`.
    ///
    /// Stops after a short page or when a later page answers 400 (past the end).
    /// You can also set an explicit end page via [`PageOptions::range`]. Items are
    /// patched and cached like `get_many`.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// use futures::StreamExt;
    ///
    /// let mut stream = client.pages::<Item>(PageOptions::default().page_size(200));
    /// while let Some(item) = stream.next().await {
    ///     let item = item?;
    ///     println!("{}", item.name);
    /// }
    /// ```
    pub(crate) fn pages<R: PagedResource + Patchable>(
        &self,
        opts: PageOptions,
    ) -> impl Stream<Item = Result<R, Gw2ApiError>> + '_ {
        stream! {
            if let Err(e) = validate_page_opts(&opts) {
                yield Err(e);
                return;
            }

            let mut page = opts.start_page;
            let total_pages: Option<u32> = opts.end_page;

            loop {
                if let Some(end) = total_pages
                    && page >= end {
                        break;
                    }

                let result: Result<Vec<R>, Gw2ApiError> = self
                    .request(format!("/{}", R::PATH))
                    .page(page, opts.page_size)
                    .send()
                    .await;

                match result {
                    Ok(mut items) => {
                        let count = items.len() as u32;
                        for item in &mut items {
                            item.patch();
                        }
                        self.cache_all(&items).await;
                        for item in items {
                            yield Ok(item);
                        }
                        // Stop if we got fewer items than requested (last page)
                        if count < opts.page_size {
                            break;
                        }
                        page += 1;
                    }
                    // A page past the end is a 400 (the API never returns an empty
                    // page). On the first page it is a real error.
                    Err(Gw2ApiError::BadRequest(_)) | Err(Gw2ApiError::NotFound(_))
                        if page > opts.start_page =>
                    {
                        break;
                    }
                    Err(e) => {
                        yield Err(e);
                        break;
                    }
                }
            }
        }
    }
}

fn validate_page_opts(opts: &PageOptions) -> Result<(), Gw2ApiError> {
    if opts.page_size == 0 || opts.page_size > 200 {
        return Err(Gw2ApiError::InvalidPagination(
            "page_size must be between 1 and 200".into(),
        ));
    }
    Ok(())
}
