//! Endpoint accessors — each module provides a typed handle
//! for a group of related API endpoints.
//!
//! Accessors are generated by `#[gw2_endpoint]` in each module.

pub mod account;
pub mod achievements;
pub mod build;
pub mod commerce;
pub mod createsubtoken;
pub mod currencies;
pub mod items;
pub mod itemstats;
pub mod minis;
pub mod mounts;
pub mod novelties;
pub mod recipes;
pub mod skills;
pub mod skins;
pub mod tokeninfo;
